### ISSUE TITLE
suggest compile error when operation use completion to suggest query co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'TermSuggestOption.score'

### ISSUE THREAD

**Issue by mini317** [elastic/elasticsearch-java#114] opened 2022-01-19 11:33 UTC
code show as below
SearchResponse<Article> search = client.search(request -> request.
                 index("test").
                 suggest(suggest -> suggest.
                         text("liu").suggesters("title_suggest",value->value.completion(v->v.
                                 field("title").skipDuplicates(false).size(10)))), Article.class);

I have tested the dsl and it works fine

**Comment by technige** [comment] 2022-01-20 14:49
Hi @mini317 

Please could you rewrite this issue to give a clear description of the problem you are seeing, your code, and expected output. Also, a short, descriptive title is much better than a long one that spans multiple lines.

Unfortunately, we cannot help until we have clarity on your issue.

**Comment by swallez** [comment] 2022-01-21 10:30
This is a duplicate of https://github.com/elastic/elasticsearch-java/issues/57

**Closed by swallez** 2022-01-21 10:30 UTC
Labels: duplicate
