### ISSUE TITLE
SearchTemplateResponse is missing aggregations

### ISSUE THREAD

**Issue by tony-hizzle** [elastic/elasticsearch-java#109] opened 2022-01-14 03:50 UTC
I have search templates that add aggregations to the response, but [SearchTemplateResponse](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/core/SearchTemplateResponse.java) does not include an aggregations field: `Map<String, Aggregate> aggregations`

```
        SearchTemplateRequest request = SearchTemplateRequest.of(r -> r
                .index("index_name")
                .id("search_template_name")
                .params(ImmutableMap.of("query_string", JsonData.of("mickey")))
        );

        SearchTemplateResponse<Map> response = elasticsearchClient.searchTemplate(request, Map.class);
```

**Comment by tony-hizzle** [comment] 2022-01-14 17:26
I guess this is a duplicate of https://github.com/elastic/elasticsearch-java/issues/89

**Comment by swallez** [comment] 2022-01-24 15:56
Indeed this is a duplicate of #89.

**Closed by swallez** 2022-01-24 15:56 UTC
Labels: duplicate
