### ISSUE TITLE
Java Client not usable for custom queries implemented as SearchPlugin

### ISSUE THREAD

**Issue by cgoller** [elastic/elasticsearch-java#138] opened 2022-01-26 10:25 UTC
With an Enum for co.elastic.clients.elasticsearch._types.query_dsl.Query.Kind it seems to be impossible to use a custom query with Java Client. 

We have implemented such a custom query via org.elasticsearch.plugins.SearchPlugin.getQueries(). It implements org.elasticsearch.index.query.QueryBuilder and we  are seeking for a way to use it with Java Client. Is this possible? If not, are you planning to make it possible?

**Comment by swallez** [comment] 2022-01-26 14:27
Thanks for the report. This is a duplicate of https://github.com/elastic/elasticsearch-java/issues/121

This is definitely something we'll add support for in a future release.

**Closed by swallez** 2022-01-26 14:27 UTC
