### ISSUE TITLE
Unable to accept negative numbers in string in search_after for epoch_millis date format

### ISSUE THREAD

**Issue by visualage** [elastic/elasticsearch-java#211] opened 2022-03-20 16:31 UTC
### Java API client version

7.17.1

### Java version

17.0

### Elasticsearch Version

7.17.1

### Problem description

When passing a string that is negative number (e.g. `"-1"`) as search_after field in search request for a `date` type sort field in `epoch_millis` date format, it refuses to accept the value, even though passing a negative integer `-1` works fine.

The fix could be that on server-side it takes negative strings, or on the client side parse `Hit.sort` as `JsonValue` so that it allows `long` type, and allow `SearchRequest.searchAfter` to take `JsonValue`. The latter also fixes https://github.com/elastic/elasticsearch-java/issues/210.

**Comment by l-trotta** [comment] 2024-01-31 11:07
We were not able to reproduce the issue, it's likely that it has been fixed with updates to the [API specification definition](https://github.com/elastic/elasticsearch-specification). Could you please check if this still happens and close the issue if not?

**Comment by l-trotta** [comment] 2024-02-21 11:28
closing this as it was most probably already fixed

**Closed by l-trotta** 2024-02-21 11:28 UTC
