### ISSUE TITLE
Complete refernce document not available for Elasticsearch new Java Client

### ISSUE THREAD

**Issue by sagarpatel07** [elastic/elasticsearch-java#256] opened 2022-04-28 10:18 UTC
### Description

There is no complete reference document available for the new Java client. We have good documentation for Java High Level client, which is deprecated now. I have check [this](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/introduction.html) documentation but it is not much useful.

- UpdateRquest example
- DeleteRequest example
- Various Index API
- Multi Search API
- Search teamplate API
- Update By Query API
- Delete By Query API

It will be gerat if we have Java client document same as Java High Level client.

**Comment by dakrone** [comment] 2022-04-28 18:59
I've transferred this to the elasticsearch-java repo, since the ES repo does not maintain the documentation for the new Java client.

**Comment by swallez** [comment] 2022-04-29 14:54
Thanks for the report. We know that documentation is still limited and will enhance it over time.

However, the "[Using the Java API client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/usage.html)" chapters that have been added recently should give you a good start into understanding how the client works. And the [API conventions](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/api-conventions.html) explain the code patterns that are used all everywhere in the Java API client.

**Comment by sagarpatel07** [comment] 2022-05-02 05:06
@swallez Thanks for the response. I have already visited link which you have shared before raising the issue. It was very difficult to migrate  High level client to the new Java Client as not enough example available. I hope over the time document will be enhanced.

**Comment by amitmbm** [comment] 2022-05-02 05:36
@swallez I totally agree with @sagarpatel07, JHLRC is deprecated, and as new java api client doesn't have enough example even for basic functionality, its causing a pain in the community, Both @sagarpatel07 and I are active on the stackOverflow community in Elasticsearch tag, and I try to organise questions related to new client, you can have a look at [this](https://stackoverflow.com/questions/tagged/elasticsearch-java-api  ) tag which is used for this purpose, and see how users are facing issue even for implementing basic functionality.

**Comment by swallez** [comment] 2022-05-02 08:58
Thanks for the link @amitmbm. I rarely look at StackOverflow (time is scarce) but this is very useful feedback.

Documentation is too limited right now, there's no question about that. However, I want to make it clear that we will not document as many APIs as in [the HLRC docs](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html). The HLRC documentation covers a lot of APIs but brings little value over the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html), except that it provides the class names for the various API objects.

The Java API client was designed with two main principles in mind:
- be very close to the Elasticsearch JSON API. To achieve this we have removed the dependencies to Elasticsearch server internals, and the client is generated from the [API specification](https://github.com/elastic/elasticsearch-specification). This guarantees consistency with everything that is explained in the Elasticsearch documentation.
- allow completion-driven discovery of APIs and their properties. The [lambada-based DSL](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/building-objects.html) is meant for that.

With that in mind, the documentation is now structured in two main areas, which will be expanded over time:
- explain the conventions used consistently (because of code generation) throughout the entire code base,
- provide use-case oriented tutorials to get started and for more advanced/less obvious Elasticsearch APIs,
- and an additional "troubleshooting/debugging" section will also be added.

There will be no exhaustive documentation of all Elasticsearch APIs similar to the HLRC docs. This is too much work for -- as I said above -- little value over the Elasticsearch documentation, in particular with the closer proximity of the Java API client with the Elasticsearch API specification.

Now we heard you loud and clear: documentation is lacking right now. It will grow, however in a different way than that of HLRC.

**Comment by amitmbm** [comment] 2022-05-02 09:20
Thanks @swallez for the very detailed feedback with the complete background, and the roadmap of the Java API client, it totally makes sense and I tried it for some of my basic POC, and I liked it as it's close to JSON API.

I am going to bookmark your explanation 😄  , it would be handy to help the community on stackOverflow. 

Looking forward to seeing more development coming in the Java API client.

**Comment by swallez** [comment] 2022-05-02 10:15
@amitmbm thanks! I also forgot to thank you for the work you do on StackOverflow. I won't have the time to be active there but I will have a closer look.

**Comment by swallez** [comment] 2022-05-05 15:04
We now have a roadmap issue for the documentation so that you can track progress and suggest additions. See https://github.com/elastic/elasticsearch-java/issues/281

**Closed by swallez** 2022-05-05 15:04 UTC
Labels: >documentation
