### ISSUE TITLE
co.elastic.clients.elasticsearch.core.SearchResponse no method searchResponseOf

### ISSUE THREAD

**Issue by Dyqer** [elastic/elasticsearch-java#240] opened 2022-04-11 02:28 UTC
### Java API client version

7.17

### Java version

7.17

### Elasticsearch Version

7.17

### Problem description

In branch 7.17, class co.elastic.clients.elasticsearch.core.SearchResponse no method searchResponseof

**Comment by l-trotta** [comment] 2024-01-31 12:25
We were not able to reproduce the issue, it's likely that it has been fixed with updates to the [API specification definition](https://github.com/elastic/elasticsearch-specification). Could you please check if this still happens and close the issue if not?

**Comment by l-trotta** [comment] 2024-02-21 11:28
closing this as it was most probably already fixed in newer versions.

**Closed by l-trotta** 2024-02-21 11:28 UTC
