### ISSUE TITLE
ElasticSearch Java API client - connection reset by peer

### ISSUE THREAD

**Issue by mohansainani** [elastic/elasticsearch-java#393] opened 2022-09-06 10:24 UTC
I have noticed that after upgrading the spring-boot service from restHighLevelClient to Java API client it is giving random connection reset by peer error, where the 1 st request always failed, later it worked and after 10 minutes this happens again. My service started and sent a query to ES and everything worked well. After 10 minutes I sent an insert request and it failed on connection reset by peer.

I have tried updating the connection timeout parameters as mentioned in the configuration [here](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.4/_timeouts.html), but it didn't work.

Any thoughts?

Error:

`org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\t... 38 common frames omitted\nCaused by: java.io.IOException: Connection reset by peer\n\tat org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:885)\n\tat org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)\n\tat org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)\n\tat co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:146)\n\tat co.elastic.clients.elasticsearch.ElasticsearchClient.index(ElasticsearchClient.java:946)\n\tat com.xxx.xxx.search.manager.data.ElasticSearchRepository.indexEntity(ElasticSearchRepository.java:51)\n\t... 52 common frames omitted\nCaused by: java.io.IOException: Connection reset by peer\n\tat sun.nio.ch.FileDispatcherImpl.read0(Native Method)\n\tat sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)\n\tat sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)\n\tat sun.nio.ch.IOUtil.read(IOUtil.java:197)\n\tat sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)\n\tat org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:478)\n\tat org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:540)\n\tat org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)\n\tat org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)\n\t... 1 common frames `

Configuration:

`

import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.json.jackson.JacksonJsonpMapper;
import co.elastic.clients.transport.ElasticsearchTransport;
import co.elastic.clients.transport.rest_client.RestClientTransport;
import org.apache.http.HeaderElement;
import org.apache.http.HeaderElementIterator;
import org.apache.http.HeaderIterator;
import org.apache.http.HttpHost;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.message.BasicHeaderElementIterator;
import org.apache.http.protocol.HTTP;
import org.elasticsearch.client.RestClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
@ConfigurationProperties(prefix = "es")
@ComponentScan(basePackages = {"pkgName"})
public class ElasticSearchConfiguration {

    private static final long DEFAULT_KEEP_ALIVE_TIME = 30 * 1000;

    @Value("#{'${es.hosts}'.split(',')}")
    private List<String> hosts;

    @Value("${es.port}")
    private Integer port;

    @Value("${es.scheme}")
    private String scheme;

    @Value("${es.username}")
    private String username;

    @Value("${es.password}")
    private String password;

    @Bean
    public ElasticsearchClient client() {
        return new ElasticsearchClient(transport());
    }

    private ElasticsearchTransport transport() {
        return new RestClientTransport(restClient(), new JacksonJsonpMapper());
    }

    @Bean
    public RestClient restClient() {
        HttpHost[] extractHosts = extractHosts(hosts, scheme);

        final CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
        credentialsProvider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials(username, password));

        return RestClient.builder(extractHosts)
                .setHttpClientConfigCallback(httpClientBuilder -> httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider).setKeepAliveStrategy((response, context) -> {
                    HeaderIterator headerIterator = response.headerIterator(HTTP.CONN_KEEP_ALIVE);
                    HeaderElementIterator elementIterator = new BasicHeaderElementIterator(headerIterator);

                    while (elementIterator.hasNext()) {
                        HeaderElement element = elementIterator.nextElement();
                        String param = element.getName();
                        String value = element.getValue();
                        if (value != null && param.equalsIgnoreCase("timeout")) {
                            return Long.parseLong(value) * 1000; // convert to ms
                        }
                    }

                    return DEFAULT_KEEP_ALIVE_TIME;
                })).setRequestConfigCallback(requestConfigBuilder -> requestConfigBuilder
                        .setConnectTimeout(10000)
                        .setSocketTimeout(60000)).build();
    }

    private HttpHost[] extractHosts(List<String> hosts, String scheme) {
        return hosts.stream().map(extractHost -> new HttpHost(extractHost, port, scheme)).toArray(HttpHost[]::new);
    }
}`

**Comment by swallez** [comment] 2022-10-13 09:53
RestHighLevelClient and Java API client both use the RestClient for http protocol handling. So this protocol error is most probably caused by a difference in the configuration of the RestClient from what you used with RestHighLevelClient. Can you double-check that?

**Comment by l-trotta** [comment] 2024-02-22 16:19
Closing this for now, please feel free to let us know if this is still an issue!

**Closed by l-trotta** 2024-02-22 16:19 UTC
