### ISSUE TITLE
The program has been running for some time, and an error is reported: too many files are opened

### ISSUE THREAD

**Issue by rouxiaoxiao** [elastic/elasticsearch-java#698] opened 2023-10-27 08:58 UTC
After configuring the client according to the official tutorial, after the deployment program interface is called a certain number of times, the program will crash and report an error, the error content: too many files are opened

**Comment by Rahuldev199** [comment] 2023-11-04 16:51
does any one looking into this issue?or is it still open?

**Comment by swallez** [comment] 2024-01-30 18:45
The issue description is not providing any information that allows to say that this is caused by the client.

The only reason this can be caused by the client is by creating a new client for each request and not closing it. This can lead to a large number of network connections to be created, which can exceed the system limits before the garbage collector cleans them up.

Please check that you use the client a singleton object. And if the problem persists, please reopen this issue with additional information that allows diagnosing the issue.

**Closed by swallez** 2024-01-30 18:45 UTC
